kind: pipeline
name: default

steps:
- name: docker  
  image: plugins/docker
  settings:
    repo: unsafetypin/guacamole
    tags: latest
    username:
      from_secret: docker_username
    password:
      from_secret: dockerhub
    when:
      branch: master