kind: pipeline
name: default

steps:
- name: docker  
  image: plugins/docker
  settings:
    repo: unsafetypin/guacamole
    tags: 1.1.0
    username:
      from_secret: docker_username
    password:
      from_secret: dockerhub
    when:
      branch: 1.1.0