stages:
  - manifest

variables:
  DOCKER_BUILDKIT: 1
  DOCKERHUB_arm64_IMAGE: unsafetypin/guacamole:1.3.0-postgres-11-arm64
  DOCKERHUB_amd64_IMAGE: unsafetypin/guacamole:1.3.0-postgres-11-amd64
  DOCKERHUB_MULTIARCH_IMAGE: unsafetypin/guacamole:1.3.0-postgres-11-MULTIARCH

manifest:
  stage: manifest
  image: docker:latest
  services:
   - name: docker:dind
     command: ["--experimental"]  
  script:
    # first make sure we have the containers we use in the manifest
    - docker pull $DOCKERHUB_amd64_IMAGE
    - docker pull $DOCKERHUB_arm64_IMAGE
    - docker manifest create $DOCKERHUB_MULTIARCH_IMAGE
        $DOCKERHUB_amd64_IMAGE
        $DOCKERHUB_arm64_IMAGE
    - docker manifest annotate --os linux --arch amd64
        $DOCKERHUB_MULTIARCH_IMAGE
        $DOCKERHUB_amd64_IMAGE
    - docker manifest annotate --os linux --arch arm64
        $DOCKERHUB_MULTIARCH_IMAGE
        $DOCKERHUB_arm64_IMAGE
    # the login to the gitlab registry sometimes times out so make sure
    # we are logged on before pushing the manifest
    - docker login -u $dockerhub_username -p $dockerhub_token
    - docker manifest push $DOCKERHUB_MULTIARCH_IMAGE
  only:
    - 1.3.0-postgres-11-multiarch
