image: docker:20-dind
services:
  - name: docker:20-dind
    alias: docker
    command: ["--tls=false"]
variables:
  DOCKER_DRIVER: overlay
  DOCKER_HOST: /var/run/docker.sock
  DOCKER_TLS_CERTDIR: ""
  IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
  FF_GITLAB_REGISTRY_HELPER_IMAGE: 1

stages:
- build
- release
- dockerhub

variables:
  TEST_IMAGE: registry.largenut.com/unsafetypin/docker-guacamole/docker-guacamole:$CI_COMMIT_REF_NAME
  RELEASE_IMAGE: registry.largenut.com/unsafetypin/docker-guacamole/docker-guacamole:latest
  DOCKERHUB_IMAGE: unsafetypin/guacamole:latest

before_script:
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.largenut.com
build:
  stage: build
  script:
    - docker build --pull -t $TEST_IMAGE .
    - docker push $TEST_IMAGE
  only:
    changes:
      - Dockerfile

release:
  stage: release
  script:
    - docker pull $TEST_IMAGE
    - docker tag $TEST_IMAGE $RELEASE_IMAGE
    - docker push $RELEASE_IMAGE
  only:
    - master
    
dockerhub:
  stage: dockerhub
  before_script:
  - docker login -u $dockerhub_username -p $dockerhub_token
  script:
    - docker pull $RELEASE_IMAGE
    - docker tag $RELEASE_IMAGE $DOCKERHUB_IMAGE
    - docker push $DOCKERHUB_IMAGE
  only:
    - master
