stages:
  - dockerhub

variables:
  DOCKER_BUILDKIT: 1
  DOCKERHUB_IMAGE: unsafetypin/guacamole:1.3.0-postgres-11-multiarch

dockerhub:
  stage: dockerhub
  image: docker:latest
  services:
   - name: docker:dind
     command: ["--experimental"]  
  script:
    - docker login -u $dockerhub_username -p $dockerhub_token
    - docker pull $CI_REGISTRY_IMAGE:1.3.0-postgres-11-multiarch
    - docker tag $CI_REGISTRY_IMAGE:1.3.0-postgres-11-multiarch $DOCKERHUB_IMAGE
    - docker push $DOCKERHUB_IMAGE
  only:
    - 1.3.0-postgres-11-multiarch


