stages:
  - create-image-amd64
  - create-image-arm64

variables:
  DOCKER_BUILDKIT: 1

create-image-amd64:
  stage: create-image-amd64
  image: docker:latest
  services:
   - name: docker:dind
     command: ["--experimental"]
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
    - docker buildx create --driver-opt network=host --use
    - docker buildx build --push --platform linux/amd64 -t $CI_REGISTRY_IMAGE:1.3.0-postgres-11-multiarch .
    - docker manifest inspect $CI_REGISTRY_IMAGE:1.3.0-postgres-11-multiarch
  only:
    - 1.3.0-postgres-11-multiarch

create-image-arm64:
  stage: create-image-arm64
  image: docker:latest
  services:
   - name: docker:dind
     command: ["--experimental"]
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
    - docker buildx create --driver-opt network=host --use
    - docker buildx build --push --platform linux/arm64 -t $CI_REGISTRY_IMAGE:1.3.0-postgres-11-multiarch .
    - docker manifest inspect $CI_REGISTRY_IMAGE:1.3.0-postgres-11-multiarch
  only:
    - 1.3.0-postgres-11-multiarch
  tags: 
    - aarch64

