stages:
  - create-image
  - dockerhub
  - manifest
  - manifest-latest

variables:
  DOCKER_BUILDKIT: 1
  DOCKERHUB_repo: unsafetypin/guacamole
  DOCKERHUB_arm64: unsafetypin/arm64
  DOCKERHUB_amd64: unsafetypin/amd64
  DOCKERHUB_arm64_IMAGE: 1.3.0-postgres-11-arm64
  DOCKERHUB_amd64_IMAGE: 1.3.0-postgres-11-amd64
  DOCKERHUB_MULTIARCH_IMAGE: 1.3.0-postgres-11
  DOCKERHUB_LATEST_IMAGE: latest

create-image-amd64:
  stage: create-image
  image: docker:latest
  services:
   - name: docker:dind
     command: ["--experimental"]
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
    - apk add curl
    - mkdir -vp ~/.docker/cli-plugins/
    - curl --silent -L "https://github.com/docker/buildx/releases/download/v0.6.3/buildx-v0.6.3.linux-amd64" > ~/.docker/cli-plugins/docker-buildx
    - chmod a+x ~/.docker/cli-plugins/docker-buildx
    - docker buildx create --driver-opt network=host --use
    - docker buildx build --push --platform linux/amd64 -t $CI_REGISTRY_IMAGE:$DOCKERHUB_amd64_IMAGE .
  only:
    refs:
      - 1.3.0-postgres-11
    changes:
      - Dockerfile

create-image-arm64:
  stage: create-image
  image: docker:latest
  services:
   - name: docker:dind
     command: ["--experimental"]
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
    - apk add curl
    - mkdir -vp ~/.docker/cli-plugins/
    - curl --silent -L "https://github.com/docker/buildx/releases/download/v0.6.3/buildx-v0.6.3.linux-arm64" > ~/.docker/cli-plugins/docker-buildx
    - chmod a+x ~/.docker/cli-plugins/docker-buildx
    - docker buildx create --driver-opt network=host --use
    - docker buildx build --push --platform linux/arm64 -t $CI_REGISTRY_IMAGE:$DOCKERHUB_arm64_IMAGE .
  only:
    refs:
      - 1.3.0-postgres-11
    changes:
      - Dockerfile
  tags: 
    - aarch64

dockerhub-amd64:
  stage: dockerhub
  image: docker:latest
  services:
   - name: docker:dind
     command: ["--experimental"]  
  script:
    - docker login -u $dockerhub_username -p $dockerhub_token
    - docker pull $CI_REGISTRY_IMAGE:$DOCKERHUB_amd64_IMAGE
    - docker tag $CI_REGISTRY_IMAGE:$DOCKERHUB_amd64_IMAGE $DOCKERHUB_amd64:$DOCKERHUB_amd64_IMAGE
    - docker push $DOCKERHUB_amd64:$DOCKERHUB_amd64_IMAGE
  only:
    - 1.3.0-postgres-11

dockerhub-arm64:
  stage: dockerhub
  image: docker:latest
  services:
   - name: docker:dind
     command: ["--experimental"]  
  script:
    - docker login -u $dockerhub_username -p $dockerhub_token
    - docker pull $CI_REGISTRY_IMAGE:$DOCKERHUB_arm64_IMAGE
    - docker tag $CI_REGISTRY_IMAGE:$DOCKERHUB_arm64_IMAGE $DOCKERHUB_arm64:$DOCKERHUB_arm64_IMAGE
    - docker push $DOCKERHUB_arm64:$DOCKERHUB_arm64_IMAGE
  only:
    - 1.3.0-postgres-11
    
manifest:
  stage: manifest
  image: docker:latest
  services:
   - name: docker:dind
     command: ["--experimental"]  
  script:
    - docker pull $DOCKERHUB_amd64:$DOCKERHUB_amd64_IMAGE
    - docker pull $DOCKERHUB_arm64:$DOCKERHUB_arm64_IMAGE
    - docker manifest create $DOCKERHUB_repo:$DOCKERHUB_MULTIARCH_IMAGE
        $DOCKERHUB_amd64:$DOCKERHUB_amd64_IMAGE
        $DOCKERHUB_arm64:$DOCKERHUB_arm64_IMAGE
    - docker manifest annotate --os linux --arch amd64
        $DOCKERHUB_repo:$DOCKERHUB_MULTIARCH_IMAGE
        $DOCKERHUB_amd64:$DOCKERHUB_amd64_IMAGE
    - docker manifest annotate --os linux --arch arm64
        $DOCKERHUB_repo:$DOCKERHUB_MULTIARCH_IMAGE
        $DOCKERHUB_arm64:$DOCKERHUB_arm64_IMAGE
    - docker login -u $dockerhub_username -p $dockerhub_token
    - docker manifest push $DOCKERHUB_repo:$DOCKERHUB_MULTIARCH_IMAGE
  only:
    - 1.3.0-postgres-11

manifest-latest:
  stage: manifest
  image: docker:latest
  services:
   - name: docker:dind
     command: ["--experimental"]  
  script:
    - docker pull $DOCKERHUB_amd64:$DOCKERHUB_amd64_IMAGE
    - docker pull $DOCKERHUB_arm64:$DOCKERHUB_arm64_IMAGE
    - docker manifest create $DOCKERHUB_repo:$DOCKERHUB_LATEST_IMAGE
        $DOCKERHUB_amd64:$DOCKERHUB_amd64_IMAGE
        $DOCKERHUB_arm64:$DOCKERHUB_arm64_IMAGE
    - docker manifest annotate --os linux --arch amd64
        $DOCKERHUB_repo:$DOCKERHUB_LATEST_IMAGE
        $DOCKERHUB_amd64:$DOCKERHUB_amd64_IMAGE
    - docker manifest annotate --os linux --arch arm64
        $DOCKERHUB_repo:$DOCKERHUB_LATEST_IMAGE
        $DOCKERHUB_arm64:$DOCKERHUB_arm64_IMAGE
    - docker login -u $dockerhub_username -p $dockerhub_token
    - docker manifest push $DOCKERHUB_repo:$DOCKERHUB_LATEST_IMAGE
  only:
    - 1.3.0-postgres-11
